#!/bin/bash


if [[ $# -eq 0 ]] ; then
    echo "Usage: $0 user project"
    exit 0
fi


scp -r include/ "root@192.168.125.1:~/Documents/KISS/$1/$2/include"
scp -r src/ "root@192.168.125.1:~/Documents/KISS/$1/$2/src"
ssh root@192.168.125.1 "gcc -I/home/root/Documents/KISS/$1/$2/include -I/usr/local/include/include -Wall /home/root/Documents/KISS/$1/$2/src/main.c /harrogate/apps/compiler/compilation-environments/c/_init_helper.c -L/usr/local/lib -lwallaby -lm -o /home/root/Documents/KISS/$1/$2/bin/botball_user_program"
